language: node_js

node_js:
  - 12

cache: npm

before_install:
  - curl -sL http://old.openzwave.com/downloads/openzwave-1.6.899.tar.gz | tar xz
  - cd openzwave-1.6.899
  - make
  - sudo make install
  - npm ci

script:
  - npm run lint
  - npm run test
